### ISSUE TITLE
Unknown Host Exception : db

### ISSUE THREAD

**Issue by pxchek** [pxchek/spring-boot-project#8]
```
Caused by: java.net.UnknownHostException: db
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source) ~[na:na]
	at java.base/java.net.Socket.connect(Unknown Source) ~[na:na]
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.PGStream.<init>(PGStream.java:98) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:109) ~[postgresql-42.3.6.jar:42.3.6]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235) ~[postgresql-42.3.6.jar:42.3.6]
	... 41 common frames omitted

pxchek0@skullcandy:~/Documents/spring-boot-project$ k get ingress
No resources found in default namespace.
pxchek0@skullcandy:~/Documents/spring-boot-project$
pxchek0@skullcandy:~/Documents/spring-boot-project$ ls -l
total 687604
drwxrwxr-x 3 pxchek0 pxchek0      4096 Aug  8 16:58 backend
-rw-rw-r-- 1 pxchek0 pxchek0       652 Aug 16 07:48 backend-deployment.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       213 Aug 16 07:48 backend-service.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       225 Aug 16 07:48 db-data-persistentvolumeclaim.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       868 Aug 16 07:48 db-deployment.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       154 Aug 16 07:48 db-pvc.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       162 Aug 16 07:48 db-pv.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       218 Aug 16 07:48 db-service.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       156 Aug 16 07:48 db-storageClass.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       508 Aug  7 07:30 docker-compose.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       250 Aug 16 07:48 networking-default-ingressclass.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       397 Aug 16 07:48 networking-minimal-ingress.yaml
-rw-rw-r-- 1 pxchek0 pxchek0       311 Aug 16 07:48 network-policy-db-access.yaml
-rw-rw-r-- 1 pxchek0 pxchek0 384060416 Aug  7 08:49 postgres.tar
-rw-rw-r-- 1 pxchek0 pxchek0       191 Aug 16 07:48 resource-quota.yaml
-rw-rw-r-- 1 pxchek0 pxchek0 319987200 Aug  7 07:48 spring-boot-project_backend.tar
```

**Comment by pxchek** [comment]
Enable the service along with the deployment

```
pxchek0@skullcandy:~/Documents/spring-boot-project$ k apply -f db-service.yaml
service/db created
pxchek0@skullcandy:~/Documents/spring-boot-project$ k get services
NAME         TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes   ClusterIP   10.152.183.1    <none>        443/TCP    9d
db           ClusterIP   10.152.183.22   <none>        5432/TCP   5s
```
